### ISSUE TITLE
x86 Slides: add diagram for x86 examples

### ISSUE THREAD

**Issue by aaronbloomfield** [aaronbloomfield/pdr#121]
- have a diagram that shows how C-style strings work for the compare_string() function
- have a diagram that shows what the stack looks like for the fib() function
- add a diagram about the little-Endian addressing benefits

**Comment by aaronbloomfield** [comment]
This did not get completed in time for the spring 2016 semester.  We are moving to 64-bit assembly for the fall.  So changing the target date for this to the fall 2016 semester, although it may not be relevant due to the assembly flavor switch

**Comment by markfloryan** [comment]
I don't think this has to do with lab 8, I believe it is intended for the x86 slideset. Changing title.

**Comment by aaronbloomfield** [comment]
Moved to https://github.com/markfloryan/pdr/issues/16
