### ISSUE TITLE
x86: lab 9 needs to be clarified

### ISSUE THREAD

**Issue by apnorton** [aaronbloomfield/pdr#123]
The inlab/postlab sections are unclear as to what students need to have completed for each deadline.  I would change this myself, but I'm actually uncertain what the proper interpretation is.  (Are they supposed to do 2 topics for the in-lab?  Or is it 2 topics total?  etc.)

**Comment by aaronbloomfield** [comment]
For this semester (fall 2015), we'll be flexible in the grading, so any "reasonable" interpretation is valid.  I'm going to target this fix for the spring 2015 semester, as I prefer not to make many changes to the labs after they have been released.
