### ISSUE TITLE
lab 7: Fix IBCM compiler issues on blank links

### ISSUE THREAD

**Issue by aaronbloomfield** [aaronbloomfield/pdr#124]
The C/C++ IBCM compiler needs to be much more lenient with blank lines, since a lot of students are running into that.  It can easily ignore them.  For that matter, it can also ignore lines that begin with `#` or `//` to allow for comments.  Consider allowing the online version to do the same (for both blank lines and comments)

**Comment by mrecachinas** [comment]
See #125

**Comment by aaronbloomfield** [comment]
This was resolved over a year ago; closing issue
