### ISSUE TITLE
lab 12: Objective C Tutorial: memory management and free

### ISSUE THREAD

**Issue by jlacomis** [aaronbloomfield/pdr#134]
`free` isn't a method in NSObject (perhaps it was at the time of writing and it isn't any more). I'm not too familiar with Objective C memory management (other than knowing it uses reference counting), but I believe that the proper way to deallocate an object created with `[SomeObject new]` is with the `release` keyword (e.g., `[SomeObject release]`).

**Comment by aaronbloomfield** [comment]
Moved to https://github.com/markfloryan/pdr/issues/15
