### ISSUE TITLE
lab 2: add another tutorial (or doc)

### ISSUE THREAD

**Issue by aaronbloomfield** [aaronbloomfield/pdr#146]
For lab 2, add a "how to debug" document (or another tutorial, or an updated tutorial).  The current tutorial assumes that they know how to debug, and it just goes over gdb or lldb, but it turns out that many students have not formally learned how to debug...

**Comment by apnorton** [comment]
I spent a few minutes looking around for a single article that describes general debugging technique.  While I haven't found one that I like yet (I'm sure I will), I thought I might make a list of related links that could be useful for 1) general reading about this topic, or 2) inspiration (if we wanted to write this tutorial from scratch).

- [Closest thing I have to a "how to debug" article](http://umich.edu/~eecs381/generalFAQ/Debugging.html)
- [Reflections on *teaching* debugging](http://blog.codeunion.io/2014/09/03/teaching-novices-how-to-debug-code/)
- [WhatHaveYouTried.com](http://mattgemmell.com/what-have-you-tried/). Honestly could be a requirement for reading before posting on Piazza. :stuck_out_tongue:

**Comment by aaronbloomfield** [comment]
I think having them read the first one is a good idea.  Thanks!
