### ISSUE TITLE
lab 12: Objective C: what to do

### ISSUE THREAD

**Issue by aaronbloomfield** [aaronbloomfield/pdr#157]
Objective C is a bit outdated.  Do we keep it in, as a means to show another way to add objects to C?  If it is kept in, then ensure the lab machines and the VB image can properly compile it.

**Comment by mrecachinas** [comment]
I argue that you should keep it in to as you stated "show another way to add objects to C". Plenty of businesses still use Objective-C due to large, legacy codebases, so it is still useful to gain exposure.

**Comment by samuelhavron** [comment]
Relevant Spring 2016 Piazza posts on Objective C compatibility with lab machines and VB image: 
[Lab machine troubles](https://piazza.com/class/ijm7w3097vt36m?cid=708)
[VB image troubles](https://piazza.com/class/ijm7w3097vt36m?cid=711)

**Comment by aaronbloomfield** [comment]
Moved to https://github.com/markfloryan/pdr/issues/10
