### ISSUE TITLE
Lab2 ListTest.cpp Issue

### ISSUE THREAD

**Issue by apnorton** [aaronbloomfield/pdr#168]
Steps:
1. Create new list (e.g. 1, 2, 3, 4)
2. Make list empty
3. Create new list (e.g. 1, 2, 3, 4)
4. Find element (e.g. "find 2")
5. Insert before
6. Segfault !?!?!

Wait, what?? :confounded:

There's some issue with ListTest.cpp and creating new lists.  I'll track this down over the weekend.

**Comment by aaronbloomfield** [comment]
When run with correct List.cpp code, this does not cause a segfault, so this seems to be an issue with the students' code.  Thus, closing issue.
