### ISSUE TITLE
Lab 5: `find()` on non-existent entries

### ISSUE THREAD

**Issue by apnorton** [aaronbloomfield/pdr#186]
We should specify whether `find()` may be called to look for a string that isn't in the tree.  If it can, then we need to specify what to do with "LeftLinksFollowed" and "RightLinksFollowed" (i.e. do we count one more link to reach the "null" terminator, or no?)

**Comment by aaronbloomfield** [comment]
Moved over to https://github.com/markfloryan/pdr/issues/5
