### ISSUE TITLE
Post Lab 6: Contradiction in timing instruction

### ISSUE THREAD

**Issue by apnorton** [aaronbloomfield/pdr#188]
The postlab for hashlab seems to have a contradiction in its timing instructions.  It says: 
> You can do this *[timing]* on any machine and data files, just use the same machine and files for all tests. Be sure to specify which files and machine you used. Show timing results (use the timer placement as we used in lab) for: *[continued]*

However, earlier it says:
> When reporting times for the post-lab report, all times must be with the words2.txt and 300x300.grid.txt files as the input. All programs must be compiled with -O2. You can do this on any computer, but make sure all your times are done on the same computer for comparison consistency. The timing code must be as specified in the pre-lab section (i.e. around the hash table usage, not the hash table creation).

**Comment by aaronbloomfield** [comment]
Moved to https://github.com/markfloryan/pdr/issues/4
