### ISSUE TITLE
include a calling convention animation

### ISSUE THREAD

**Issue by aaronbloomfield** [aaronbloomfield/pdr#55]
an animation of how memory (registers and the stack) changes as the cpu progresses through a calling convention example would help them understand it better

**Comment by mrecachinas** [comment]
This looks relevant -- you might find a portion out of these that you could show:

- https://www.youtube.com/watch?v=B56PXXA_a3E
- https://www.youtube.com/watch?v=KRaJoeVXF_8
- https://www.youtube.com/watch?v=eUykMiutX8A
- https://www.youtube.com/watch?v=kSgrKtA0rJM
