### ISSUE TITLE
handle the nasm tutorial

### ISSUE THREAD

**Issue by aaronbloomfield** [aaronbloomfield/pdr#58]
The original link died (although the links to the tutorial are not consistent, and at least one of them point sto a new 64-bit tutorial).  Either find the old version (internet archive?), ask to incldue it in the repo, or create one.

**Comment by mrecachinas** [comment]
Old Version: https://web.archive.org/web/20120414223112/http://www.cs.lmu.edu/~ray/notes/nasmexamples

**Comment by aaronbloomfield** [comment]
I'm going to leave this issue open for a bit, as I want to investiage including that tutorial entirely in this repo...

**Comment by aaronbloomfield** [comment]
The tutorial no longer is available (except the Internet Archive) -- and the author's website seems to be no longer available.  The material in the two book chapters seems to exceed what is in the tutorial.  Thus, I'm going to remove that link entirely from the repo, and replace it with the book chapters...
