### ISSUE TITLE
provide more "bootstrapping" guidance

### ISSUE THREAD

**Issue by aaronbloomfield** [aaronbloomfield/pdr#76]
to start on lab 1, they need to clone the git repo.  but to see how to clone the git repo, they need to read the lab.  so it's a bit of a cycle

this immediate problem can be solved by providing a link to lab 1 or tutorial 1 on github

but an overall introduction to git, and the `git clone` and `git pull` commands would help

**Comment by mrecachinas** [comment]
Solution: do toposort first. 😛

**Comment by aaronbloomfield** [comment]
Solution is to post the http://aaronbloomfield.github.io/pdr link in the daily announcements
