### ISSUE TITLE
fix the lab 1 / tutorial 1 intro to unix section

### ISSUE THREAD

**Issue by aaronbloomfield** [aaronbloomfield/pdr#77]
it's a bit out of date, and some are finding it confusing; from an anonymous feedback send on 1-16-15:

>  The introduction to UNIX tutorial seems to feel a bit out of date and seems to have some confusingly written parts (i.e. when explaining how to launch Emacs, "...the easy way is to load up a command shell (which you will need anyway), and enter 'emacs &' (note the 'x' at the beginning, and the ampersand ('&') at the end)." I was confused about the statement about the 'x' that wasn't there (simply 'emacs &', with no 'x' ended up being the correct command statement). Also, my Emacs already had colored font and line-number-mode enabled and didn't require M-x prompts. Also, at the end of the tutorial the link to the Emacs reference sheet doesn't load, and the file is not under the misc folder in Resources as described. These are just a few that stood out to me when I was going through the tutorial. Though in spite of this, I was still able to get through the tutorial without much trouble so I suppose it's somewhat trivial. Thanks in advance.

**Comment by mrecachinas** [comment]
Check out #84 - I updated the tutorial.

**Comment by aaronbloomfield** [comment]
Thanks for the updates!  When I have a bit more time (likely over the summer), I want to read over the entire tutorial a few times and do some edits; leaving this issue open until then

**Comment by mrecachinas** [comment]
👍

**Comment by aaronbloomfield** [comment]
This seems to be all resolved!
