### ISSUE TITLE
lab 2: main() function modification

### ISSUE THREAD

**Issue by aaronbloomfield** [aaronbloomfield/pdr#80]
From an anonymous feedback:

> the test client doesn't support testing the `last()` method in List (to get a ListItr); that could be useful to have. A way of directly calling makeEmpty() from the test client would be nice as well.

**Comment by mrecachinas** [comment]
See if the fix in #84 is what you were thinking.

**Comment by aaronbloomfield** [comment]
Resolved via pull request #84
