### ISSUE TITLE
add an integer / binary overflow slide

### ISSUE THREAD

**Issue by aaronbloomfield** [aaronbloomfield/pdr#83]
At the end of the integer section of 03-numbers, there should be a slide that explains why adding 1 to the 8-bit signed int 127 yields -128 (and likewise for 16-bit and 32-bit numbers).  This would also help explain [xkcd 571](http://xkcd.com/571/)

**Comment by mrecachinas** [comment]
Relevant: http://www.cs.utah.edu/~regehr/papers/overflow12.pdf
