### ISSUE TITLE
Lab10 has conflicting information in inlab vs. postlab

### ISSUE THREAD

**Issue by apnorton** [aaronbloomfield/pdr#92]
Lab10's inlab says, in part:
> You will need to get the Huffman decoder working when you submit the in-lab, as you will not be submitting it again for the post-lab. If you cannot get it working during the in-lab time, then you should request a lab extension, and submit what you have done so far.

However, the postlab requests all of the encoder/decoder code to be resubmitted:
> If your pre-lab and in-lab code work properly, then there is no futher clean-up to do; however, you must still submit the files along with a new Makefile.

I'd resolve this myself, but I wasn't sure to what extent the inlab should insist on having the decoder work properly. (e.g. "you die if you don't get it working" vs. "it would be ideal" vs. all the options in between)

**Comment by apnorton** [comment]
As an aside, if this isn't the proper channel for reporting issues of this kind, please let me know.

**Comment by aaronbloomfield** [comment]
Right venue!  This was a change made this semester, and I obviously didn't read through the entire lab doc.  Fixing it now.  Thanks!
